### PR TITLE
Update vscode textmate

### LINKED ISSUE #4: `node bin/highlighter.js highlight` command seems to be broken
`Highlighter.new` calls `registry.loadGrammarFromPathSync()`, which no longer seems to exist in the vscode-textmate version specified in `package.json` (4.1.1). It looks like the static `patchFile()`  / `patchFolder()` functions don't go through that code path (I assume that's what's used on haxe.org?).

Sidenote: it would be nice if there was a way to use `patchFolder()` via the CLI (looks like it currently only accepts single files).

### PR DESCRIPTION
**Pull request by tobil4sk**
Required some api changes, I've updated the readme accordingly.

Closes #4.

### CODE REVIEW

**Comment by kLabz** [comment]
@ibilon would it be possible to have this reviewed/merged? It would help us with Haxe websites :)
Thanks!

**Comment by ibilon** [comment]
Thank you for the update @tobil4sk!

**Comment by ibilon** [comment]
I've pushed the new version to haxelib.

**Comment by tobil4sk** [comment]
Thanks for merging and updating the package!

**Pull request merged**
